### ISSUE TITLE
RAPTOR_Clustering() takes no arguments

### ISSUE THREAD

**Issue by chenyujiang11** [parthsarthi03/raptor#2]
I encountered an error when I imported a relatively long txt file. I did not encounter this error when using the txt in the demo. Could you please tell me how to deal with this problem. Thank you very much.

Traceback (most recent call last):
  File "/home/jyc23/raptor-master/demo/demo.py", line 132, in <module>
    RA.add_documents(text)
  File "/home/jyc23/raptor-master/raptor/RetrievalAugmentation.py", line 217, in add_documents
    self.tree = self.tree_builder.build_from_text(text=docs)
  File "/home/jyc23/raptor-master/raptor/tree_builder.py", line 280, in build_from_text
    root_nodes = self.construct_tree(all_nodes, all_nodes, layer_to_nodes)
  File "/home/jyc23/raptor-master/raptor/cluster_tree_builder.py", line 102, in construct_tree
    clusters = self.clustering_algorithm.perform_clustering(
  File "/home/jyc23/raptor-master/raptor/cluster_utils.py", line 226, in perform_clustering
    RAPTOR_Clustering(
TypeError: RAPTOR_Clustering() takes no arguments

**Comment by parthsarthi03** [comment]
Hi, thank you for bringing this to our attention. https://github.com/parthsarthi03/raptor/commit/7a9e83fd7f166bb82841aa4fa17313bd1ef1b297 resolves the issue.

**Comment by ATP-BME** [comment]
How to ensure that the requirements of max_length_in_cluster can be satisfied after clustering with the same parameters? The current program seems at risk of becoming trapped in an infinite loop
